### ISSUE TITLE
Unable to start without provding keepalived.conf

### ISSUE THREAD

**Issue by ekiel** [rvben/rpi-keepalived#1]
I was passing environmentals with this command and found that it would not generate a keepalived.conf

If I run without presenting a keepalived.conf via -v /home/pi/keepalived.conf:/etc/keepalived.conf it errored out:
+ set -e
+ CONFIG=/etc/keepalived/keepalived.conf
+ grep -q '{{' /etc/keepalived/keepalived.conf
+ sed -i 's|{{ STATE }}|BACKUP|g' /etc/keepalived/keepalived.conf
+ sed -i 's|{{ ROUTER_ID }}|41|g' /etc/keepalived/keepalived.conf
+ sed -i 's|{{ INTERFACE }}|eth0|g' /etc/keepalived/keepalived.conf
+ sed -i 's|{{ PRIORITY }}|100|g' /etc/keepalived/keepalived.conf
+ sed -i 's|{{ PASSWORD }}|KeptAliv|g' /etc/keepalived/keepalived.conf
+ '[' -n /notify.sh ']'
+ sed -i 's|{{ NOTIFY }}|notify "/notify.sh"|g' /etc/keepalived/keepalived.conf
+ chmod +x /notify.sh
+ for peer in $UNICAST_PEERS
+ sed -i 's|{{ UNICAST_PEERS }}|192.168.0.30\n    {{ UNICAST_PEERS }}|g' /etc/keepalived/keepalived.conf
+ for peer in $UNICAST_PEERS
+ sed -i 's|{{ UNICAST_PEERS }}|192.168.0.31\n    {{ UNICAST_PEERS }}|g' /etc/keepalived/keepalived.conf
+ for peer in $UNICAST_PEERS
+ sed -i 's|{{ UNICAST_PEERS }}|192.168.0.32\n    {{ UNICAST_PEERS }}|g' /etc/keepalived/keepalived.conf
+ sed -i '|{{ UNICAST_PEERS }}|d' /etc/keepalived/keepalived.conf
sed: unsupported command |

here is the command I used to start this container:
docker run --name keepalived --cap-add=NET_ADMIN --net=host -d -e UNICAST_PEERS='192.168.0.30 192.168.0.31 192.168.0.32' -e VIRTUAL_IPS=192.168.0.35/24 rvben/rpi-keepalived

Any help would be greatly appreciated!

**Comment by rvben** [comment]
Hello,

Thanks a lot for raising this issue. I tested it and found out that using a pipe symbol as delimiters for the sed command doesn't work properly for deletion. I changed them to the default slashes and now it should work properly. Can you please check and verify?

Kind regards,

Ruben

**Comment by ekiel** [comment]
Thanks for getting back to me! I tried it again, and it still terminates - _I should note I did a pull docker rvben/rpi-keepalived and it grabbed the new image too!_
```
pi@moby1:~ $ docker run --name keepalived --cap-add=NET_ADMIN --net=host -d -e UNICAST_PEERS='192.168.0.30 192.168.0.31 192.168.0.32' -e VIRTUAL_IPS=192.168.0.36/24 rvben/rpi-keepalived
fea6ca466109dce658ab3d1a978af6094e67ebca012ae82db9f8acac1923ba52
pi@moby1:~ $ docker logs keepalived
+ set -e
+ CONFIG=/etc/keepalived/keepalived.conf
+ grep -q '{{' /etc/keepalived/keepalived.conf
+ sed -i 's|{{ STATE }}|BACKUP|g' /etc/keepalived/keepalived.conf
+ sed -i 's|{{ ROUTER_ID }}|41|g' /etc/keepalived/keepalived.conf
+ sed -i 's|{{ INTERFACE }}|eth0|g' /etc/keepalived/keepalived.conf
+ sed -i 's|{{ PRIORITY }}|100|g' /etc/keepalived/keepalived.conf
+ sed -i 's|{{ PASSWORD }}|KeptAliv|g' /etc/keepalived/keepalived.conf
+ '[' -n /notify.sh ']'
+ sed -i 's|{{ NOTIFY }}|notify "/notify.sh"|g' /etc/keepalived/keepalived.conf
+ chmod +x /notify.sh
+ for peer in $UNICAST_PEERS
+ sed -i 's|{{ UNICAST_PEERS }}|192.168.0.30\n    {{ UNICAST_PEERS }}|g' /etc/keepalived/keepalived.conf
+ for peer in $UNICAST_PEERS
+ sed -i 's|{{ UNICAST_PEERS }}|192.168.0.31\n    {{ UNICAST_PEERS }}|g' /etc/keepalived/keepalived.conf
+ for peer in $UNICAST_PEERS
+ sed -i 's|{{ UNICAST_PEERS }}|192.168.0.32\n    {{ UNICAST_PEERS }}|g' /etc/keepalived/keepalived.conf
+ sed -i '/{{ UNICAST_PEERS }}/d' /etc/keepalived/keepalived.conf
+ for vip in $VIRTUAL_IPS
+ sed -i 's|{{ VIRTUAL_IPS }}|192.168.0.36/24\n    {{ VIRTUAL_IPS }}|g' /etc/keepalived/keepalived.conf
+ sed -i '/{{ VIRTUAL_IPS }}/d' /etc/keepalived/keepalived.conf
+ exec /usr/local/sbin/keepalived -f /etc/keepalived/keepalived.conf --dont-fork --log-console
Wed Aug 22 03:40:07 2018: Starting Keepalived v2.0.5 (06/29,2018)
Wed Aug 22 03:40:07 2018: Running on Linux 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 (built for Linux 4.4.6)
Wed Aug 22 03:40:07 2018: Opening file '/etc/keepalived/keepalived.conf'.
Wed Aug 22 03:40:07 2018: Starting VRRP child process, pid=22
Wed Aug 22 03:40:07 2018: Registering Kernel netlink reflector
Wed Aug 22 03:40:07 2018: Registering Kernel netlink command channel
Wed Aug 22 03:40:07 2018: Opening file '/etc/keepalived/keepalived.conf'.
Wed Aug 22 03:40:07 2018: *** Configuration line starting `notify` is missing a parameter after keyword `notify` at word position 2
Wed Aug 22 03:40:07 2018: Keepalived_vrrp exited with permanent error CONFIG. Terminating
Wed Aug 22 03:40:07 2018: Stopping
Wed Aug 22 03:40:07 2018: Stopped Keepalived v2.0.5 (06/29,2018)
```

If there are any other logs or anything else I can test let me know! I'm pretty new to this but if I pass 
`-v /home/pi/docker_configs/keepalived/keepalived.conf:/etc/keepalived/keepalived.conf`
and I use the following file it works great! 
```
vrrp_instance VI_1 {
    state MASTER
    interface eth0
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass sekret
    }
    virtual_ipaddress {
        192.168.0.35
    }
}
```

**Comment by rvben** [comment]
Good day,

Thanks for your testing. Really appreciated. :) 

I used your variables, and started the container in interactive mode so I could run the entrypoint script, and keep the shell. I read the keepalived.conf and found the issue. The 'notify' option was not set correctly in the template file.
Can you verify that it's now fixed?

Thanks again,

Ruben

**Comment by ekiel** [comment]
It works as expected now! Thank you for taking the time to look at this!
